create or replace view test_dbt.stg_product
  
  as
    

-- Generated by dbtvault.



WITH source_data AS (

    SELECT

    PRODUCT_ID,
    PRODUCT_DESC

    FROM test_dbt.raw_product
),

derived_columns AS (

    SELECT

    PRODUCT_ID,
    PRODUCT_DESC,
    '1SAP' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DATETIME

    FROM source_data
),

hashed_columns AS (

    SELECT

    PRODUCT_ID,
    PRODUCT_DESC,
    RECORD_SOURCE,
    LOAD_DATETIME,

    SHA2(NULLIF(UPPER(TRIM(CAST(PRODUCT_ID AS STRING))), ''), 256) AS CUSTOMER_HK,
    SHA2(CONCAT_WS('||',
        IFNULL(NULLIF(UPPER(TRIM(CAST(PRODUCT_DESC AS STRING))), ''), '^^')
    ), 256) AS CUSTOMER_HASHDIFF

    FROM derived_columns
),

columns_to_select AS (

    SELECT

    PRODUCT_ID,
    PRODUCT_DESC,
    RECORD_SOURCE,
    LOAD_DATETIME,
    CUSTOMER_HK,
    CUSTOMER_HASHDIFF

    FROM hashed_columns
)

SELECT * FROM columns_to_select
