create or replace view test_dbt.stg_customer
  
  as
    

-- Generated by dbtvault.



WITH source_data AS (

    SELECT

    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL

    FROM test_dbt.raw_customer
),

derived_columns AS (

    SELECT

    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    '1SAP' AS RECORD_SOURCE,
    CURRENT_TIMESTAMP() AS LOAD_DATETIME

    FROM source_data
),

hashed_columns AS (

    SELECT

    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    RECORD_SOURCE,
    LOAD_DATETIME,

    SHA2(NULLIF(UPPER(TRIM(CAST(CUSTOMER_ID AS STRING))), ''), 256) AS CUSTOMER_HK,
    SHA2(CONCAT_WS('||',
        IFNULL(NULLIF(UPPER(TRIM(CAST(EMAIL AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(FIRST_NAME AS STRING))), ''), '^^'),
        IFNULL(NULLIF(UPPER(TRIM(CAST(LAST_NAME AS STRING))), ''), '^^')
    ), 256) AS CUSTOMER_HASHDIFF

    FROM derived_columns
),

columns_to_select AS (

    SELECT

    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    RECORD_SOURCE,
    LOAD_DATETIME,
    CUSTOMER_HK,
    CUSTOMER_HASHDIFF

    FROM hashed_columns
)

SELECT * FROM columns_to_select
